language: go
go:
  - '1.10'
branches:
  only:
    - master
    - /\Av\d+\.\d+\.\d+\z/
before_deploy:
  - make package
deploy:
  provider: releases
  api_key:
    secure: JplGW8MS1N1SQlRhE0Wx//8lDCamAVTmB3mUbGYUdvL3oBr2ouMt6E9HR/n9QREDhaTwxNWw8vv4Mm1pqDRTFLCBORoZbqlBXbgE/23GQw+YAXSUPk95kPouuj8+hRegzV1vyGMKFlgpJVFVCMH5uv8iUVlKiw2JuIlIoS66UnXXcU6gCiEnHpzQNKD3B6AEN/F/Q5vYdjEig+TZuBwx/ioXCaaAs6ai1NlHHwS5HWEWgLRjlpa9lJTKosok3klg3levraKbS7aQJ92ucAmCkiYwWRoEOnSbdDizmcYNOwcuP6b01gnRp11wlQq5hivbc9LPkfQC6waHL0jSK5n315PgEzVKM/YwYrVL+tU6TGTjugGdcre8LKehbn7RrGqG+VcvUeeHIfGQLNGACfOmkO954ALFakjVBVSWdVxv3hXtm+tbXjhZSpPDW8xU+D6lF9zdLO71JnJjYPJ9yfkA8UD0h5lH2VUDpb6233aUyNpWB792HUK4eFmtoFQexpzSCzv2otYF7rUoCi8flZiaIcYRGp76ZV+jbZ6ReMC8eVO/maJmChkLUpkuvYUStyyayzzGYMIIBMDk62ycjNbLRwAVgYXW3sqQmuz+rtECqOj0H02LxAGJWiMlWDs2c4SBbfmlue8yLPZIOaO6ZAQJ0qpOBqHsE8+T9hkgXwzIl+w=
  file_glob: true
  file: package/*
  skip_cleanup: true
  on:
    repo: tsuty/make-shadow
    tags: true
