language: go
go:
  - '1.10'
branches:
  only:
    - master
    - /\Av\d+\.\d+\.\d+\z/
before_deploy:
  - make package
deploy:
  provider: releases
  api_key:
    secure: iRkn/XKmxTs96nxEoIbXwXqhvf/bwWqZ8W3uuJPWq8ZUWGrrMB5uc7v/EP2cTirCQ1tVvo1RhgMpzMl2BWaEkwRRBRjYKtUWrMYd7spJkX9OhchS5HiakpGKGy84XqNIcoZRls4fZiO6k7jWKRYx5Ol7sumbeWtZ7c318zTqrdtpkMnKvGzfP5FcvXmLK4e2XsYb7YZwa8xB8d/K21Bg8z/K0lypjytQ4tmyHDhVgl4MH/4Op0dZg8freYofUaneVbq5jHZMsw6IGkDr8X9jejRNrdftLI+9kAUeXKwMVL2E7s0ydyPYD7GwDW6NBhGjnRMl4qx76BXL0moAFnBo6dDo6ELRUmTrgD0RuXwgHwz3oMzKm0v/2j2jxRX2WGYPW/aynNF29zHpBpDCm5r/HEFTRIueoNP7z0MTC6O4ueFLCuEoDqhERGGB58wKz5h6dWUFsAGwXzUFHmWcYRTYF2WiKB0S3PyzEptriqL6+tm/0oGyE/qH2U3ZyLoUtwvRSsAZ7+HO7bRwLleYJmabxf8FvSYOkM8kqTCOxp9cWlQA+KnT9wOIhiGutrzcgACmZ7ygCFoiuGI5ZVhhVDDAoXe4Zy1CZF7vSnWXhqdj544Spa7vJNlt/qb+PxkiZo9iTiwTckRxqkQ7jpvnAoP0EVP5FwS7TTSiz0ayztNJ4ZE=
  file_glob: true
  file: package/*
  skip_cleanup: true
  on:
    repo: tsuty/make-shadow
    tags: true
