language: go
go:
  - '1.10'
branches:
  only:
    - master
    - /\Av\d+\.\d+\.\d+\z/
before_deploy:
  - make package
deploy:
  provider: releases
  api_key:
    secure: h/kaqm1cVY4d9L6Xoh0Uku1K0PfQrDtUNUA7hTJXnYbk1VeoJ+1ak6IXhe2EOqCmDGgJJd4c5gXuZYVUgWK7JH72KgqNl6YYbgEDxJNsJeQgLRzWFVpo29GWMtRQ7fbAsASw7FXvmOimYIsNJXCmrtDjBCN6C3K13KXg02rF1lR0sKjUOvlN30bvTWkSapvcoIKer+lhDHpFYjfHqhXfcGvzN0mMJhwzmBpO+pcIgC2Rk0EyJAqDPCcE+C/QVpNHa/LaaCG8JJhiJ/hlGiKI19k8HgYuBGgy8ZbthzvOebCICLavl45a08v+H+q2fE5ra8tfhejfoWB+flh4MkvAiGplT/kAgmCPGjU3RQ6xcQvvGWhT2UzfuBlH2U2JTXkyG69QM1M0omoqcrGBsyqQFNVumOSfcOTWgm2TkxkbpBCV6fXvWQmJyp7zeJXVXcW5S5XgWqxmI5YYNQ4v1O+euigIBABD4Kea8iDyE6SuxV3RtecBvHq7zbDfasQuem+uqugn7hadmGZztnnrJP4hkRsPmnEqICzWpTGAXsbBc+ja6LqvVuHbmddushwujk6zvjC8xQU+/BuiTOTr5RBJgPs3AjEarnaNvBp9ygjwCs+JRBQaMcb8zUVa1B1NW0WSWYPce5ksa+ZHvualmBCDFep9yvlLDAnAZim0lau9718=
  file: package/*
  skip_cleanup: true
  on:
    repo: tsuty/make-shadow
    tags: true
