language: go
go:
  - '1.13'
branches:
  only:
    - /\Av\d+\.\d+\.\d+\z/
before_deploy:
  - make package
deploy:
  provider: releases
  api_key:
    secure: cOoCvw+AR1R9A8CY0dOrwqNPmzVrQYztKpu5UHVofDQNglcv7TRh8ymHFdpDzFddZbrPS+poKfICnEoRkoYb6E71f0pQnr8nWkHVkLgILZn8P3FbmSubM7BFoft1m4YH6Y9PECaEtVhU6i+z2BJAZMuWErmvPBu4yPINM3jkvfpsXcjGlFmP8gw7KdgRO2YriJt+uLfuiZF2JycnlTC8WzVXfYYwMJjiFEzE4Ar1+YBYIo2Vy9txxgy0Na5pnX6qfanTRRXhiC8TfIWJ4jUAQ4Y/wevHl55RrNlCLBcFgVmFTUanuycuAYooSJhhOaSWawrTMkkDCxWMxdEGgRBKjJ5eUy34AmAinUQwkOHLhXhVeJPRJaNaItauuo2oVphiLsN/LKHpzbBhFyvuhIui5Qx5SBphIgX9Au036t8zM5h3p7p/w6lXUTOg96DnQYH5vpKcT08gwS5LdiQeHsct8eRjFX07qRso1xhgtO6svPvnn5lgK0jOPSs/ceUNeN398yzShEAE3tZqzO6zxgocdST8LD9ZdZSJeGMnzj/2DU7t/u+bcCgTz979jBpT10MkUpKaRpOxm41tPqOYi+H1MgQ+/c9uvzbA1GnThTaCIwV3KYTSpmbXm1eonA4RwZIGT8bgmE/2pe5G/3Y6YnG9/h5HF1ePHA0bXyJj4XjaHaM=
  file_glob: true
  file: package/*
  skip_cleanup: true
  on:
    repo: tsuty/make-shadow
    tags: true
